-- local status, lualine = pcall(require, "lualine")
--
-- if not status then
-- 	return
-- end
--
-- local lualine_ayu_mirage = require("lualine.themes.modus-vivendi")
--
-- lualine.setup({
-- 	options = {
-- 		theme = lualine_ayu_mirage,
-- 	},
-- })
