#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d     
bspc config border_width         5
bspc config window_gap          10

bspc config top_padding 75 
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Color changes
bspc config normal_border_color \#181825
bspc config focused_border_color \#e6e9ef

bspc rule -a '*' state=floating

#bspc rule -a mpv state=tiled
bspc rule -a zathura state=tiled
bspc rule -a qutebrowser state=tiledAutostart applications

sxhkd &
picom --config $HOME/.config/picom/picom.conf &
nitrogen --restore &
dunst &
polybar &
# Do not put this here
# xrandr --output eDP-1 --mode 2560x1440 --rate 60
