;==========================================================
[gruvbox]
black= #000000
dark= #1d1d1d
disabled= #262626
red=#fff4d2
red-alt=#fff4d2
orange=#fff4d2
orange-mat=#fff4d2
yellow=#fff4d2
yellow-mat=#fff4d2
green=#fff4d2
green-alt=#fff4d2
aqua=#fff4d2
aqua-alt=#fff4d2
blue=#fff4d2
blue-alt=#fff4d2
grey=#fff4d2
dark-grey=#222222
cream= #fff4d2
white= #cdd6f4
base= #24273a
surface0= #363a4f
transparent= #00000000
Stransparent= #CC000000
mauve=#fff4d2 
lavendar=#fff4d2 
teal=#fff4d2 
mantle= #181825
